### ISSUE TITLE
Troubleshooting Installation

### ISSUE THREAD

**Issue by JChen2857** [scikit-garden/scikit-garden#46] opened 2017-09-05 13:57 UTC
Hi,

I tried installing using pip install scikit-garden and ran into the following error message:

pip install scikit-garden
Collecting scikit-garden
  Using cached scikit-garden-0.1.3.tar.gz
Requirement already satisfied: numpy in c:\users\jchen\appdata\local\continuum\anaconda2\lib\site-packages (from scikit-garden)
Requirement already satisfied: scipy in c:\users\jchen\appdata\local\continuum\anaconda2\lib\site-packages (from scikit-garden)
Requirement already satisfied: scikit-learn>=0.18 in c:\users\jchen\appdata\local\continuum\anaconda2\lib\site-packages (from scikit-garden)
Requirement already satisfied: cython in c:\users\jchen\appdata\local\continuum\anaconda2\lib\site-packages (from scikit-garden)
Building wheels for collected packages: scikit-garden
  Running setup.py bdist_wheel for scikit-garden ... error
  Complete output from command C:\Users\jchen\AppData\Local\Continuum\Anaconda2\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\jchen\\appdata\\local\\temp\\pip-build-6becp0\\scikit-garden\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d c:\users\jchen\appdata\local\temp\tmpmvmkfopip-wheel- --python-tag cp27:
  Appending skgarden.mondrian.tree configuration to skgarden.mondrian
  Ignoring attempt to set 'name' (from 'skgarden.mondrian' to 'skgarden.mondrian.tree')
  Appending skgarden.mondrian.ensemble configuration to skgarden.mondrian
  Ignoring attempt to set 'name' (from 'skgarden.mondrian' to 'skgarden.mondrian.ensemble')
  Appending skgarden.mondrian configuration to skgarden
  Ignoring attempt to set 'name' (from 'skgarden' to 'skgarden.mondrian')
  Appending skgarden.quantile configuration to skgarden
  Ignoring attempt to set 'name' (from 'skgarden' to 'skgarden.quantile')
  Appending skgarden configuration to
  Ignoring attempt to set 'name' (from '' to 'skgarden')
  running bdist_wheel
  running build
  running config_cc
  unifing config_cc, config, build_clib, build_ext, build commands --compiler options
  running config_fc
  unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
  running build_src
  build_src
  building extension "skgarden.mondrian.tree._tree" sources
  building extension "skgarden.mondrian.tree._splitter" sources
  building extension "skgarden.mondrian.tree._criterion" sources
  building extension "skgarden.mondrian.tree._utils" sources
  build_src: building npy-pkg config files
  running build_py
  creating build
  creating build\lib.win-amd64-2.7
  creating build\lib.win-amd64-2.7\skgarden
  copying skgarden\forest.py -> build\lib.win-amd64-2.7\skgarden
  copying skgarden\setup.py -> build\lib.win-amd64-2.7\skgarden
  copying skgarden\__init__.py -> build\lib.win-amd64-2.7\skgarden
  creating build\lib.win-amd64-2.7\skgarden\mondrian
  copying skgarden\mondrian\setup.py -> build\lib.win-amd64-2.7\skgarden\mondrian
  copying skgarden\mondrian\__init__.py -> build\lib.win-amd64-2.7\skgarden\mondrian
  creating build\lib.win-amd64-2.7\skgarden\quantile
  copying skgarden\quantile\ensemble.py -> build\lib.win-amd64-2.7\skgarden\quantile
  copying skgarden\quantile\setup.py -> build\lib.win-amd64-2.7\skgarden\quantile
  copying skgarden\quantile\tree.py -> build\lib.win-amd64-2.7\skgarden\quantile
  copying skgarden\quantile\utils.py -> build\lib.win-amd64-2.7\skgarden\quantile
  copying skgarden\quantile\__init__.py -> build\lib.win-amd64-2.7\skgarden\quantile
  creating build\lib.win-amd64-2.7\skgarden\mondrian\ensemble
  copying skgarden\mondrian\ensemble\forest.py -> build\lib.win-amd64-2.7\skgarden\mondrian\ensemble
  copying skgarden\mondrian\ensemble\setup.py -> build\lib.win-amd64-2.7\skgarden\mondrian\ensemble
  copying skgarden\mondrian\ensemble\__init__.py -> build\lib.win-amd64-2.7\skgarden\mondrian\ensemble
  creating build\lib.win-amd64-2.7\skgarden\mondrian\tree
  copying skgarden\mondrian\tree\setup.py -> build\lib.win-amd64-2.7\skgarden\mondrian\tree
  copying skgarden\mondrian\tree\tree.py -> build\lib.win-amd64-2.7\skgarden\mondrian\tree
  copying skgarden\mondrian\tree\__init__.py -> build\lib.win-amd64-2.7\skgarden\mondrian\tree
  running build_ext
  customize MSVCCompiler
  customize MSVCCompiler using build_ext
  building 'skgarden.mondrian.tree._tree' extension
  compiling C sources
  creating build\temp.win-amd64-2.7
  creating build\temp.win-amd64-2.7\Release
  creating build\temp.win-amd64-2.7\Release\skgarden
  creating build\temp.win-amd64-2.7\Release\skgarden\mondrian
  creating build\temp.win-amd64-2.7\Release\skgarden\mondrian\tree
  C:\Users\jchen\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Users\jchen\AppData\Local\Continuum\Anaconda2\lib\site-packages\numpy\core\include -IC:\Users\jchen\AppData\Local\Continuum\Anaconda2\lib\site-packages\numpy\core\include -IC:\Users\jchen\AppData\Local\Continuum\Anaconda2\include -IC:\Users\jchen\AppData\Local\Continuum\Anaconda2\PC /Tcskgarden\mondrian\tree\_tree.c /Fobuild\temp.win-amd64-2.7\Release\skgarden\mondrian\tree\_tree.obj -O3
  Found executable C:\Users\jchen\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe

  C:\Users\jchen\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\link.exe /DLL /nologo /INCREMENTAL:NO /LIBPATH:C:\Users\jchen\AppData\Local\Continuum\Anaconda2\libs /LIBPATH:C:\Users\jchen\AppData\Local\Continuum\Anaconda2\PCbuild\amd64 /LIBPATH:C:\Users\jchen\AppData\Local\Continuum\Anaconda2\PC\VS9.0\amd64 /EXPORT:init_tree build\temp.win-amd64-2.7\Release\skgarden\mondrian\tree\_tree.obj /OUT:build\lib.win-amd64-2.7\skgarden\mondrian\tree\_tree.pyd /IMPLIB:build\temp.win-amd64-2.7\Release\skgarden\mondrian\tree\_tree.lib /MANIFESTFILE:build\temp.win-amd64-2.7\Release\skgarden\mondrian\tree\_tree.pyd.manifest
  Found executable C:\Users\jchen\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\link.exe
  _tree.obj : warning LNK4197: export 'init_tree' specified multiple times; using first specification
     Creating library build\temp.win-amd64-2.7\Release\skgarden\mondrian\tree\_tree.lib and object build\temp.win-amd64-2.7\Release\skgarden\mondrian\tree\_tree.exp
  _tree.obj : error LNK2019: unresolved external symbol fmax referenced in function __pyx_f_8skgarden_8mondrian_4tree_5_tree_4Tree_predict
  build\lib.win-amd64-2.7\skgarden\mondrian\tree\_tree.pyd : fatal error LNK1120: 1 unresolved externals
  error: Command "C:\Users\jchen\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\link.exe /DLL /nologo /INCREMENTAL:NO /LIBPATH:C:\Users\jchen\AppData\Local\Continuum\Anaconda2\libs /LIBPATH:C:\Users\jchen\AppData\Local\Continuum\Anaconda2\PCbuild\amd64 /LIBPATH:C:\Users\jchen\AppData\Local\Continuum\Anaconda2\PC\VS9.0\amd64 /EXPORT:init_tree build\temp.win-amd64-2.7\Release\skgarden\mondrian\tree\_tree.obj /OUT:build\lib.win-amd64-2.7\skgarden\mondrian\tree\_tree.pyd /IMPLIB:build\temp.win-amd64-2.7\Release\skgarden\mondrian\tree\_tree.lib /MANIFESTFILE:build\temp.win-amd64-2.7\Release\skgarden\mondrian\tree\_tree.pyd.manifest" failed with exit status 1120

  ----------------------------------------
  Failed building wheel for scikit-garden
  Running setup.py clean for scikit-garden
Failed to build scikit-garden
Installing collected packages: scikit-garden
  Running setup.py install for scikit-garden ... error
    Complete output from command C:\Users\jchen\AppData\Local\Continuum\Anaconda2\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\jchen\\appdata\\local\\temp\\pip-build-6becp0\\scikit-garden\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\jchen\appdata\local\temp\pip-xcrp8b-record\install-record.txt --single-version-externally-managed --compile:
    Appending skgarden.mondrian.tree configuration to skgarden.mondrian
    Ignoring attempt to set 'name' (from 'skgarden.mondrian' to 'skgarden.mondrian.tree')
    Appending skgarden.mondrian.ensemble configuration to skgarden.mondrian
    Ignoring attempt to set 'name' (from 'skgarden.mondrian' to 'skgarden.mondrian.ensemble')
    Appending skgarden.mondrian configuration to skgarden
    Ignoring attempt to set 'name' (from 'skgarden' to 'skgarden.mondrian')
    Appending skgarden.quantile configuration to skgarden
    Ignoring attempt to set 'name' (from 'skgarden' to 'skgarden.quantile')
    Appending skgarden configuration to
    Ignoring attempt to set 'name' (from '' to 'skgarden')
    running install
    running build
    running config_cc
    unifing config_cc, config, build_clib, build_ext, build commands --compiler options
    running config_fc
    unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
    running build_src
    build_src
    building extension "skgarden.mondrian.tree._tree" sources
    building extension "skgarden.mondrian.tree._splitter" sources
    building extension "skgarden.mondrian.tree._criterion" sources
    building extension "skgarden.mondrian.tree._utils" sources
    build_src: building npy-pkg config files
    running build_py
    creating build
    creating build\lib.win-amd64-2.7
    creating build\lib.win-amd64-2.7\skgarden
    copying skgarden\forest.py -> build\lib.win-amd64-2.7\skgarden
    copying skgarden\setup.py -> build\lib.win-amd64-2.7\skgarden
    copying skgarden\__init__.py -> build\lib.win-amd64-2.7\skgarden
    creating build\lib.win-amd64-2.7\skgarden\mondrian
    copying skgarden\mondrian\setup.py -> build\lib.win-amd64-2.7\skgarden\mondrian
    copying skgarden\mondrian\__init__.py -> build\lib.win-amd64-2.7\skgarden\mondrian
    creating build\lib.win-amd64-2.7\skgarden\quantile
    copying skgarden\quantile\ensemble.py -> build\lib.win-amd64-2.7\skgarden\quantile
    copying skgarden\quantile\setup.py -> build\lib.win-amd64-2.7\skgarden\quantile
    copying skgarden\quantile\tree.py -> build\lib.win-amd64-2.7\skgarden\quantile
    copying skgarden\quantile\utils.py -> build\lib.win-amd64-2.7\skgarden\quantile
    copying skgarden\quantile\__init__.py -> build\lib.win-amd64-2.7\skgarden\quantile
    creating build\lib.win-amd64-2.7\skgarden\mondrian\ensemble
    copying skgarden\mondrian\ensemble\forest.py -> build\lib.win-amd64-2.7\skgarden\mondrian\ensemble
    copying skgarden\mondrian\ensemble\setup.py -> build\lib.win-amd64-2.7\skgarden\mondrian\ensemble
    copying skgarden\mondrian\ensemble\__init__.py -> build\lib.win-amd64-2.7\skgarden\mondrian\ensemble
    creating build\lib.win-amd64-2.7\skgarden\mondrian\tree
    copying skgarden\mondrian\tree\setup.py -> build\lib.win-amd64-2.7\skgarden\mondrian\tree
    copying skgarden\mondrian\tree\tree.py -> build\lib.win-amd64-2.7\skgarden\mondrian\tree
    copying skgarden\mondrian\tree\__init__.py -> build\lib.win-amd64-2.7\skgarden\mondrian\tree
    running build_ext
    customize MSVCCompiler
    customize MSVCCompiler using build_ext
    building 'skgarden.mondrian.tree._tree' extension
    compiling C sources
    creating build\temp.win-amd64-2.7
    creating build\temp.win-amd64-2.7\Release
    creating build\temp.win-amd64-2.7\Release\skgarden
    creating build\temp.win-amd64-2.7\Release\skgarden\mondrian
    creating build\temp.win-amd64-2.7\Release\skgarden\mondrian\tree
    C:\Users\jchen\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Users\jchen\AppData\Local\Continuum\Anaconda2\lib\site-packages\numpy\core\include -IC:\Users\jchen\AppData\Local\Continuum\Anaconda2\lib\site-packages\numpy\core\include -IC:\Users\jchen\AppData\Local\Continuum\Anaconda2\include -IC:\Users\jchen\AppData\Local\Continuum\Anaconda2\PC /Tcskgarden\mondrian\tree\_tree.c /Fobuild\temp.win-amd64-2.7\Release\skgarden\mondrian\tree\_tree.obj -O3
    Found executable C:\Users\jchen\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe
    C:\Users\jchen\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\link.exe /DLL /nologo /INCREMENTAL:NO /LIBPATH:C:\Users\jchen\AppData\Local\Continuum\Anaconda2\libs /LIBPATH:C:\Users\jchen\AppData\Local\Continuum\Anaconda2\PCbuild\amd64 /LIBPATH:C:\Users\jchen\AppData\Local\Continuum\Anaconda2\PC\VS9.0\amd64 /EXPORT:init_tree build\temp.win-amd64-2.7\Release\skgarden\mondrian\tree\_tree.obj /OUT:build\lib.win-amd64-2.7\skgarden\mondrian\tree\_tree.pyd /IMPLIB:build\temp.win-amd64-2.7\Release\skgarden\mondrian\tree\_tree.lib /MANIFESTFILE:build\temp.win-amd64-2.7\Release\skgarden\mondrian\tree\_tree.pyd.manifest
    Found executable C:\Users\jchen\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\link.exe
    _tree.obj : warning LNK4197: export 'init_tree' specified multiple times; using first specification
       Creating library build\temp.win-amd64-2.7\Release\skgarden\mondrian\tree\_tree.lib and object build\temp.win-amd64-2.7\Release\skgarden\mondrian\tree\_tree.exp

Looks like there is something wrong with Visual C++ for python. Any help would be greatly appreciated. Thanks!

**Comment by JChen2857** [comment] 2017-09-05 14:04
I have tried reinstalling the Microsoft Visual C++ compiler for Python 2.7 and I am still running into the same error. Here is the more 'verbose' error message:

C:\Users\jchen\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Users\jchen\AppData\Local\Continuum\Anaconda2\lib\site-packages\numpy\core\include -IC:\Users\jchen\AppData\Local\Continuum\Anaconda2\lib\site-packages\numpy\core\include -IC:\Users\jchen\AppData\Local\Continuum\Anaconda2\include -IC:\Users\jchen\AppData\Local\Continuum\Anaconda2\PC /Tcskgarden\mondrian\tree\_tree.c /Fobuild\temp.win-amd64-2.7\Release\skgarden\mondrian\tree\_tree.obj -O3
  Found executable C:\Users\jchen\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe

  C:\Users\jchen\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\link.exe /DLL /nologo /INCREMENTAL:NO /LIBPATH:C:\Users\jchen\AppData\Local\Continuum\Anaconda2\libs /LIBPATH:C:\Users\jchen\AppData\Local\Continuum\Anaconda2\PCbuild\amd64 /LIBPATH:C:\Users\jchen\AppData\Local\Continuum\Anaconda2\PC\VS9.0\amd64 /EXPORT:init_tree build\temp.win-amd64-2.7\Release\skgarden\mondrian\tree\_tree.obj /OUT:build\lib.win-amd64-2.7\skgarden\mondrian\tree\_tree.pyd /IMPLIB:build\temp.win-amd64-2.7\Release\skgarden\mondrian\tree\_tree.lib /MANIFESTFILE:build\temp.win-amd64-2.7\Release\skgarden\mondrian\tree\_tree.pyd.manifest
  Found executable C:\Users\jchen\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\link.exe
  _tree.obj : warning LNK4197: export 'init_tree' specified multiple times; using first specification
     Creating library build\temp.win-amd64-2.7\Release\skgarden\mondrian\tree\_tree.lib and object build\temp.win-amd64-2.7\Release\skgarden\mondrian\tree\_tree.exp
  _tree.obj : error LNK2019: unresolved external symbol fmax referenced in function __pyx_f_8skgarden_8mondrian_4tree_5_tree_4Tree_predict
  build\lib.win-amd64-2.7\skgarden\mondrian\tree\_tree.pyd : fatal error LNK1120: 1 unresolved externals
  error: Command "C:\Users\jchen\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\link.exe /DLL /nologo /INCREMENTAL:NO /LIBPATH:C:\Users\jchen\AppData\Local\Continuum\Anaconda2\libs /LIBPATH:C:\Users\jchen\AppData\Local\Continuum\Anaconda2\PCbuild\amd64 /LIBPATH:C:\Users\jchen\AppData\Local\Continuum\Anaconda2\PC\VS9.0\amd64 /EXPORT:init_tree build\temp.win-amd64-2.7\Release\skgarden\mondrian\tree\_tree.obj /OUT:build\lib.win-amd64-2.7\skgarden\mondrian\tree\_tree.pyd /IMPLIB:build\temp.win-amd64-2.7\Release\skgarden\mondrian\tree\_tree.lib /MANIFESTFILE:build\temp.win-amd64-2.7\Release\skgarden\mondrian\tree\_tree.pyd.manifest" failed with exit status 1120

  ----------------------------------------
  Failed building wheel for scikit-garden
  Running setup.py clean for scikit-garden
Failed to build scikit-garden
Installing collected packages: scikit-garden
  Running setup.py install for scikit-garden ... error
    Complete output from command C:\Users\jchen\AppData\Local\Continuum\Anaconda2\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\jchen\\appdata\\local\\temp\\pip-build-rkyovq\\scikit-garden\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\jchen\appdata\local\temp\pip-tnrz0c-record\install-record.txt --single-version-externally-managed --compile:
    Appending skgarden.mondrian.tree configuration to skgarden.mondrian
    Ignoring attempt to set 'name' (from 'skgarden.mondrian' to 'skgarden.mondrian.tree')
    Appending skgarden.mondrian.ensemble configuration to skgarden.mondrian
    Ignoring attempt to set 'name' (from 'skgarden.mondrian' to 'skgarden.mondrian.ensemble')
    Appending skgarden.mondrian configuration to skgarden
    Ignoring attempt to set 'name' (from 'skgarden' to 'skgarden.mondrian')
    Appending skgarden.quantile configuration to skgarden
    Ignoring attempt to set 'name' (from 'skgarden' to 'skgarden.quantile')
    Appending skgarden configuration to
    Ignoring attempt to set 'name' (from '' to 'skgarden')
    running install
    running build
    running config_cc
    unifing config_cc, config, build_clib, build_ext, build commands --compiler options
    running config_fc
    unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
    running build_src
    build_src
    building extension "skgarden.mondrian.tree._tree" sources
    building extension "skgarden.mondrian.tree._splitter" sources
    building extension "skgarden.mondrian.tree._criterion" sources
    building extension "skgarden.mondrian.tree._utils" sources
    build_src: building npy-pkg config files
    running build_py
    creating build
    creating build\lib.win-amd64-2.7
    creating build\lib.win-amd64-2.7\skgarden
    copying skgarden\forest.py -> build\lib.win-amd64-2.7\skgarden
    copying skgarden\setup.py -> build\lib.win-amd64-2.7\skgarden
    copying skgarden\__init__.py -> build\lib.win-amd64-2.7\skgarden
    creating build\lib.win-amd64-2.7\skgarden\mondrian
    copying skgarden\mondrian\setup.py -> build\lib.win-amd64-2.7\skgarden\mondrian
    copying skgarden\mondrian\__init__.py -> build\lib.win-amd64-2.7\skgarden\mondrian
    creating build\lib.win-amd64-2.7\skgarden\quantile
    copying skgarden\quantile\ensemble.py -> build\lib.win-amd64-2.7\skgarden\quantile
    copying skgarden\quantile\setup.py -> build\lib.win-amd64-2.7\skgarden\quantile
    copying skgarden\quantile\tree.py -> build\lib.win-amd64-2.7\skgarden\quantile
    copying skgarden\quantile\utils.py -> build\lib.win-amd64-2.7\skgarden\quantile
    copying skgarden\quantile\__init__.py -> build\lib.win-amd64-2.7\skgarden\quantile
    creating build\lib.win-amd64-2.7\skgarden\mondrian\ensemble
    copying skgarden\mondrian\ensemble\forest.py -> build\lib.win-amd64-2.7\skgarden\mondrian\ensemble
    copying skgarden\mondrian\ensemble\setup.py -> build\lib.win-amd64-2.7\skgarden\mondrian\ensemble
    copying skgarden\mondrian\ensemble\__init__.py -> build\lib.win-amd64-2.7\skgarden\mondrian\ensemble
    creating build\lib.win-amd64-2.7\skgarden\mondrian\tree
    copying skgarden\mondrian\tree\setup.py -> build\lib.win-amd64-2.7\skgarden\mondrian\tree
    copying skgarden\mondrian\tree\tree.py -> build\lib.win-amd64-2.7\skgarden\mondrian\tree
    copying skgarden\mondrian\tree\__init__.py -> build\lib.win-amd64-2.7\skgarden\mondrian\tree
    running build_ext
    customize MSVCCompiler
    customize MSVCCompiler using build_ext
    building 'skgarden.mondrian.tree._tree' extension
    compiling C sources
    creating build\temp.win-amd64-2.7
    creating build\temp.win-amd64-2.7\Release
    creating build\temp.win-amd64-2.7\Release\skgarden
    creating build\temp.win-amd64-2.7\Release\skgarden\mondrian
    creating build\temp.win-amd64-2.7\Release\skgarden\mondrian\tree
    C:\Users\jchen\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Users\jchen\AppData\Local\Continuum\Anaconda2\lib\site-packages\numpy\core\include -IC:\Users\jchen\AppData\Local\Continuum\Anaconda2\lib\site-packages\numpy\core\include -IC:\Users\jchen\AppData\Local\Continuum\Anaconda2\include -IC:\Users\jchen\AppData\Local\Continuum\Anaconda2\PC /Tcskgarden\mondrian\tree\_tree.c /Fobuild\temp.win-amd64-2.7\Release\skgarden\mondrian\tree\_tree.obj -O3
    Found executable C:\Users\jchen\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe
    C:\Users\jchen\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\link.exe /DLL /nologo /INCREMENTAL:NO /LIBPATH:C:\Users\jchen\AppData\Local\Continuum\Anaconda2\libs /LIBPATH:C:\Users\jchen\AppData\Local\Continuum\Anaconda2\PCbuild\amd64 /LIBPATH:C:\Users\jchen\AppData\Local\Continuum\Anaconda2\PC\VS9.0\amd64 /EXPORT:init_tree build\temp.win-amd64-2.7\Release\skgarden\mondrian\tree\_tree.obj /OUT:build\lib.win-amd64-2.7\skgarden\mondrian\tree\_tree.pyd /IMPLIB:build\temp.win-amd64-2.7\Release\skgarden\mondrian\tree\_tree.lib /MANIFESTFILE:build\temp.win-amd64-2.7\Release\skgarden\mondrian\tree\_tree.pyd.manifest
    Found executable C:\Users\jchen\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\link.exe
    _tree.obj : warning LNK4197: export 'init_tree' specified multiple times; using first specification
       Creating library build\temp.win-amd64-2.7\Release\skgarden\mondrian\tree\_tree.lib and object build\temp.win-amd64-2.7\Release\skgarden\mondrian\tree\_tree.exp
    _tree.obj : error LNK2019: unresolved external symbol fmax referenced in function __pyx_f_8skgarden_8mondrian_4tree_5_tree_4Tree_predict
    build\lib.win-amd64-2.7\skgarden\mondrian\tree\_tree.pyd : fatal error LNK1120: 1 unresolved externals
    error: Command "C:\Users\jchen\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\link.exe /DLL /nologo /INCREMENTAL:NO /LIBPATH:C:\Users\jchen\AppData\Local\Continuum\Anaconda2\libs /LIBPATH:C:\Users\jchen\AppData\Local\Continuum\Anaconda2\PCbuild\amd64 /LIBPATH:C:\Users\jchen\AppData\Local\Continuum\Anaconda2\PC\VS9.0\amd64 /EXPORT:init_tree build\temp.win-amd64-2.7\Release\skgarden\mondrian\tree\_tree.obj /OUT:build\lib.win-amd64-2.7\skgarden\mondrian\tree\_tree.pyd /IMPLIB:build\temp.win-amd64-2.7\Release\skgarden\mondrian\tree\_tree.lib /MANIFESTFILE:build\temp.win-amd64-2.7\Release\skgarden\mondrian\tree\_tree.pyd.manifest" failed with exit status 1120

    ----------------------------------------
Command "C:\Users\jchen\AppData\Local\Continuum\Anaconda2\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\jchen\\appdata\\local\\temp\\pip-build-rkyovq\\scikit-garden\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\jchen\appdata\local\temp\pip-tnrz0c-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\jchen\appdata\local\temp\pip-build-rkyovq\scikit-garden\

**Comment by dougalsutherland** [comment] 2017-09-07 10:43
@JChen2857 Your error messages would be clearer to read if you put a ` ``` ` line (three backticks) before and after them, to format them as code.

But the problem is this: `error LNK2019: unresolved external symbol fmax referenced in function`, which is the same problem as #41 and was solved by #44 in the development version -- it just hasn't been in a new release yet. If you try installing the development version with `pip install 'git+https://github.com/scikit-garden/scikit-garden`, that problem at least should be fixed. I'm expecting it to then break with #48, though. :)

**Comment by JChen2857** [comment] 2017-09-07 14:58
@dougalsutherland Thanks for the help and the formatting advice. I tried installing the development version and it seems to be working for me.

**Closed** 2017-09-07 17:00 UTC
